### ISSUE TITLE
Support custom loggers

### ISSUE THREAD

**Issue by a3957273** [karolyp/docker-tar-pusher#3]
Would be useful to have the ability to take in a logger, even if it's just a very simple:

```
logger: (msg: string) => void
```

This would let us integrate the module into our existing bunyan logger.

**Comment by karolyp** [comment]
Hi @a3957273 ,

Thank you for your suggestion. It is part of [v2.0.1](https://github.com/karolyp/docker-tar-pusher/releases/tag/v2.0.1).
I have also provided an [example](https://github.com/karolyp/docker-tar-pusher#complete-example-with-custom-logger), feel free to check out and give some feedback, if this is what you wanted.

Thanks!
